# Generated by Django 5.2.3 on 2025-06-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=100)),
                ('issue', models.CharField(max_length=200)),
                ('device', models.CharField(max_length=100)),
                ('maintenance_type', models.CharField(max_length=100)),
                ('employee', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('delivery_time', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
