# Generated by Django 5.2.3 on 2025-06-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_maintenancerecord_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='date_time',
            field=models.DateTimeField(verbose_name='وقت الاستلام'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='delivery_time',
            field=models.DateTimeField(verbose_name='وقت التسليم'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='device',
            field=models.CharField(max_length=100, verbose_name='نوع الجهاز'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='employee',
            field=models.CharField(max_length=100, verbose_name='اسم الموظف'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='issue',
            field=models.CharField(max_length=200, verbose_name='نوع العطل'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='maintenance_type',
            field=models.CharField(choices=[('صيانة هواتف', '📱 صيانة هواتف'), ('صيانة تجميعات', '💻 صيانة تجميعات'), ('صيانة أجهزة الألعاب', '🎮 صيانة أجهزة الألعاب')], max_length=100, verbose_name='نوع الصيانة'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الزبون'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='price',
            field=models.CharField(max_length=100, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='receiver',
            field=models.CharField(max_length=100, verbose_name='موظف الاستلام'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='status',
            field=models.CharField(choices=[('قيد الفحص', '🔍 قيد الفحص'), ('قيد الصيانة', '🛠️ قيد الصيانة'), ('جاهز للاستلام', '✅ جاهز للاستلام'), ('تم التسليم', '📦 تم التسليم')], max_length=50, verbose_name='حالة الجهاز'),
        ),
    ]
