# Generated by Django 5.2.3 on 2025-06-20 03:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_maintenancerecord_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت الاستلام'),
        ),
    ]
